### ISSUE TITLE
File overwrite description

### ISSUE THREAD

**Issue by scripting** [scripting/drummerSupport#127] opened 2021-11-28 16:36 UTC
### Narration

I just had one file overwrite another. 

I had a bunch of files open, including these three:

1. menubar.opml

2. scratchpad.opml

3. blog.opml

I was going back and forth between scratchpad and menubar, editing a script, and running it against a section of scratchpad.

I was also reloading the Drummer app a lot, because I was making changes to the app, implementing a new verb. 

scratchpad is a very large file. (Or it was, until the overwrite. I also have it backed up, and also the contents is considered disposable. It's just a place where I try stuff out.)

I activated scratchpad and noticed its title had changed to Scripts, and the contents was the contents of menubar.opml.

I hovered the cursor over the file icon in the tab, and the file was called scratchpad.opml. 

I looked in the JavaScript console. Saw no errors, and the activations you would expect. 

### Discussion

There was an instant outline open, the change notes outline, but there had been no updates happening around the time this problem happened, although there were some earlier. I think it's very unlikely that the I/O was the source of this overwrite. Which is new data, because I had been assuming that the problem was in I/O background updates. 

I also had blog.opml open, and was doing stuff there, but not in this "run" of Drummer (ie since the last hard reload).

The unusual thing that had happened was I was editing menubar.opml, which was causing the Scripts menu to rebuild. But I'm not sure it happened in this run.

**Comment by fmcpherson** [comment] 2021-11-29 21:18
I think I caused a similar problem to occur a while ago in Little Outliner by switching tabs before a changed OPML file was saved. My recollection is the following. Assume you have two files open, one in tab A the other in tab B. Make edits in Tab A then quickly click Tab B. What I observed is that if I click Tab B too soon, I assume before the changes are saved, the contents in Tab A overwrites the contents of the file open in Tab B but the file name of the file open in Tab B remains the same. 

I had a backup of the file, so I made a mental note to pay attention to the "Not Saved" and "Saved" status messages and not switch between tabs too fast while editing, and went on my way assuming operator error.

**Comment by scripting** [comment] 2021-11-29 21:23
Frank this is not LO2. A whole new tab system.

**Comment by PostMonsterG** [comment] 2021-11-30 00:32
This has happened to me many times. I cannot reproduce it reliably, which is why I have not filed, I am sorry.

I hate it when people speculate about how code works when they don't know the internals, so I am super reluctant to post here. But I put some speculation in a thread on Twitter the other day. https://twitter.com/postmonsterg/status/1463551539562172422?s=10

I suspect—if this is how Drummer works internally, and I have no idea—that it may be due to using time stamps with one-second resolution as IDs. This is based on my vague recollection of comments Dave has made regarding copy-pasting nodes to be used as bookmarks. (In addition to the bookmarks menu, I am not sure I trust pinning 100 percent.)

Again, this is pure speculation, and really unlikely to help, since I don't know how Drummer works inside. I apologize for wasting anybody's time, or giving anyone the wrong idea about how Drummer might operate inside.

**Comment by scripting** [comment] 2021-11-30 02:21
I'm not sure if people saw [my post on Scripting News](http://scripting.com/2021/11/29.html#a213511), earlier. I'm most interested right now in knowing if people were editing the Scripts menu (menubar.opml) around the time they saw an overwrite. Here's the text of the post. 

> Yesterday I had one of my Drummer outlines overwrite another. There were no instant outlines updating while this happened, so that's not the source of the problem. If you've had this happen: 1. I am sorry this is happening, that's first. 2. Make sure you do backups. 3. Were you by any chance editing [the Scripts menu](http://docserver.scripting.com/drummer/scripting.opml#1627490175000) when this happened? If so, please comment here. I'm looking for more clues. I added more debugging code so if it happens to me again, I'll get closer to knowing that the cause is. I really want to get this bug out of there.

**Comment by PostMonsterG** [comment] 2021-11-30 02:50
My menubar.opml has been open in a tab for the past week or so. This weekend, I had a file get replaced with the contents of another file (possibly just the pinned section of another file). I hadn't touched the file that got its contents replaced in at least several hours. Nor had I edited menubar.opml in several days. I was not executing any Drumkit intended to modify tabs, or open or save files.

**Comment by PostMonsterG** [comment] 2021-11-30 18:21
I've had more of these wormhole incidents than I can count, dating back to mid-October, when I started using Drummer. Anecdotes aren't repro steps, which is why I haven't filed. Maybe anecdotes will help, sorry. Here's a bit more about the one from Saturday.

Several tabs open, the ones I was mostly using were

 - Docserver lookup source, where I work on my Drumkit
 - Icon bar outline

The work flow was:

 - Modify Drumkit script in source tab
 - Copy top-level node
 - Switch to icon bar tab
 - Select script currently under "question" heading
 - Delete it
 - Paste new script
 - Tab it into place
 - Switch back to source tab
 - Test the script

I put a video on my blog of the script I was working with. You can see some of the other tabs, actually, which included—

- The wormhole tab, which I no longer go near
- Menu bar tab, which I don't close anymore because it's right next to the wormhole tab, and I can never remember if closing it will switch focus to the wormhole tab. I was not working in the menu bar file this weekend.

I am not sure if the other tabs visible in the video were open at the time. The file I lost, my scratchpad file, was not open. When it was time to make my Drumkit pose for a video, I selected my scratchpad file from my bookmarks menu, so I could work on the blog post describing it. 

Rather than the contents of the blog I'd been working on, I found a chunk of code. I don't remember what chunk it was, but it was my code, and it looked like I'd pinned a function. My video shows some of my typical use patterns.

(At this point, I made a new scratchpad file, recovered the contents from a backup, and moved on.)

I just now opened the old scratchpad file. There is now nothing in it, which was really surprising. Not even the snippet of Drumkit I'd seen before.

 - The title of the tab is now "// Get the D...", which corresponds to the header of a section of my code. 
 - In the file browser, the file showed as non-zero, but small, in size. The scratchpad should be 200K or something, it showed like 5K or something.
 - The contents of the file are empty now
 - The info at the bottom says Created: 11/27/2021 at 1:07:25 PM, length=0 

Some additional notes—
 - The file I lost was named "scratchpad.opml"
 - I've lost files not named "scratchpad.opml"
 - The earliest incident I can recall is back in October, shortly after I started using Drummer. An outline got replaced with the contents of the DW menu. The only scripting I'd done with Drummer to that point was adding the cloud-up arrow icon to build my blog, as described in the tutorial. I do not recall if I had menu.opml or iconbar.opml or bookmarks.opml open at the time.
 - I'd had other files replaced with the contents of the DW menu. This did not turn the file into a live outline.
 - At one point, I had my blog.opml file replaced with the contents of my icon bar file. As part of recovering from a backup, I noted that the opml headers in the corrupted file were from the icon bar. That is, after I replaced the file from the backup, the blog was still titled "ICONBAR" instead of "This is the blog part."

I'm really sorry I do not have repro steps for this, I've tried, this is a super important bug for me, and I've been trying to nail it down for weeks.

**Closed** 2021-11-30 19:34 UTC
